### ISSUE TITLE
SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by NeVroe** [4dams/CryptoCurrency#3]
Within a couple of hours the bot is throwing below error.

undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/home/user/tmp/CryptoCurrency/app.js:56:21)
    at self.callback (/home/user/tmp/CryptoCurrency/node_modules/request/request                                    .js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/home/user/tmp/CryptoCurrency/node_modules/reques                                    t/request.js:878:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)

**Comment by 4dams** [comment]
Hm... That's really strange... It seems to be an error occurring with the request module. 

A temporary workaround for that would be using "pm2" to automatically restart the bot when errors occur or it crashes.

Thanks for reporting the issue!

**Comment by NeVroe** [comment]
Np, thanks for the workaround!

**Comment by 4dams** [comment]
That's really strange, I started to run the bot myself yesterday evening, when I saw your ticket and haven't had a single crash/restart yet. 

Would you mind sending me a list of modules you are using?

In the meanwhile, you can also invite my hosted version to your server! [Here's the invite link!](https://discordapp.com/oauth2/authorize?client_id=329331452040708096&scope=bot) (Make sure to give the bot proper permission to chat in your channel, etc.)
